In [10]:
import numpy as np

# Precision

In [8]:
numbers = np.array([1, 2, 3])
numbers

array([1, 2, 3])

By default, `numpy` does floating-point operations as double-precision (64 bits)

In [3]:
type(numbers), type(numbers[0])

(numpy.ndarray, numpy.int64)

In [9]:
numbers

array([1, 2, 3])

However, by default the parameters in `TF.Keras` model are single-precision floating-point (32 bits). 32-bits precision is generally more than enough for neural networks. Plus it runs faster and uses less RAM [^1].

For efficiency, convert the np array to 32 bits by using the numpy `astype` method. Otherwise, the matrix multiplication would take double the number of machine cycles (64 x 32 instead of 32 x 32).

[^1]: https://stackoverflow.com/questions/60044519/convert-a-tensor-into-numpy-array-but-with-higher-precision#:~:text=This%20is%20because%2032%2Dbit%20precision%20is%20generally%20more%20than%20enough%20for%20neural%20networks%2C%20plus%20it%20runs%20faster%20and%20uses%20less%20RAM.

In [7]:
numbers.astype("float32")

array([1., 2., 3.], dtype=float32)